export const en = {
  "hintText": {
    "fileName": "Enter File Name",
    "alias": "Enter Display Name",
    "newItem": "+ New",
    "selectNote": "Select Note...",
    "createListItem": "Create List Item",
    "dragDropProperties": "Drag and drop to reorder properties",
    "dragDropModifierKeys": "Hold Alt to copy",
    "hiddenExtensionsPlaceholder": "e.g., .mdb, _assets"
  },
  "timeUnits": {
    "hour": "Hour",
    "day": "Day",
    "week": "Week",
    "month": "Month",
    "year": "Year",
    "minute": "Minute",
    "second": "Second"
  },
  "aggregates": {
    "values": "Values",
    "sum": "Sum",
    "average": "Average",
    "median": "Median",
    "count": "Count",
    "countValues": "Count Values",
    "countUniques": "Count Uniques",
    "percentageEmpty": "Percentage Empty",
    "percentageNotEmpty": "Percentage Not Empty",
    "min": "Min",
    "max": "Max",
    "range": "Range",
    "empty": "Empty",
    "notEmpty": "Not Empty",
    "earliest": "Earliest",
    "latest": "Latest",
    "complete": "Complete",
    "incomplete": "Not Complete",
    "percentageComplete": "Percentage Complete",
    "dateRange": "Date Range"
  },
  "fieldTypes": {
    "object": "Object",
    "text": "Text",
    "file": "File",
    "date": "Date",
    "number": "Number"
  },
  "defaults": {
    "spaceNote": "Current Note",
    "spaceContext": "Current Space"
  },
  "commands": {
    "h1": "Heading 1",
    "h2": "Heading 2",
    "h3": "Heading 3",
    "h4": "Heading 4",
    "h5": "Heading 5",
    "h6": "Heading 6",
    "columns": "Columns",
    "tabs": "Tabs",
    "button": "Button",
    "label": "Label",
    "column": "Column",
    "idea": "New",
    "group": "Group",
    "paragraph": "Text",
    "card": "Card",
    "cardDesc": "Card container with styled background",
    "progress": "Progress",
    "rating": "Rating",
    "circularProgress": "Circular Progress",
    "list": "Bullet List",
    "ordered-list": "Numbered List",
    "todo": "To-do List",
    "quote": "Quote",
    "internal": "Link to Note",
    "context": "Embed Existing Context",
    "flowEmbed": "Embed Note or Space",
    "board": "New Board",
    "divider": "Divider",
    "note": "Note Block",
    "link": "Web Link",
    "internalLink": "Link",
    "callout": "Callout",
    "bookmark": "Bookmark",
    "table": "New Table",
    "codeblock": "Code Block",
    "toggle": "Toggle",
    "emoji": "Emoji",
    "image": "Image",
    "chart": "Chart",
    "newNote": "Note",
    "tag": "Tag",
    "makeMenu": "Flow Menu",
    "selectStyle": "Style",
    "toggleKeyboard": "Toggle Keyboard",
    "flow": "Flow"
  },
  "styles": {
    "blocklink": "Link to Note",
    "textColor": "Text Color",
    "highlight": "Highlight"
  },
  "commandsSuggest": {
    "noResult": "No result"
  },
  "commandPalette": {
    "openFlow": "Open Flow Blocks in Selection",
    "closeFlow": "Close Flow Blocks in Selection",
    "openSpaces": "Open Spaces",
    "blink": "Blink",
    "revealFile": "Reveal File in Spaces",
    "pinActiveFileToSpace": "Pin Active File to Space",
    "convertPathToSpace": "Convert Path to Space"
  },
  "frames": {
    "label": {
      "label": "Label",
      "description": "Label"
    },
    "context": {
      "label": "Context",
      "description": "Display a context view from another space"
    },
    "calendar": {
      "label": "Calendar View"
    },
    "event": {
      "label": "Event"
    },
    "divider": {
      "label": "Divider",
      "description": "Divider to separate your content"
    },
    "button": {
      "label": "Button",
      "description": "Buttons can perform actions and open links"
    },
    "toggle": {
      "description": "Toggle to show/hide content"
    }
  },
  "menu": {
    "createItemInSpace": "Create Item in Space",
    "newItemView": "New Item View",
    "noActionsAvailable": "No Actions Available",
    "path": "Path",
    "name": "Name",
    "content": "Content",
    "property": "Property",
    "value": "Value",
    "table": "Table",
    "click": "Click",
    "hover": "Hover",
    "align": "Align",
    "shadow": "Shadow",
    "noFramesAvailable": "No Frames Available",
    "tabName": "Tab Name",
    "removeTab": "Remove Tab",
    "items": "Items",
    "metadata": "Metadata",
    "special": "Special",
    "cardContainerWithStyledBackground": "Card Container With Styled Background",
    "buttonContainerWithStyledAppearance": "Button Container With Styled Appearance",
    "up": "Up",
    "down": "Down",
    "selectmenu": "Selectmenu",
    "toggle": "Toggle",
    "setDefaultSticker": "Set Default Sticker",
    "setDefaultColor": "Set Default Color",
    "new": "New",
    "noColorPalettesAvailable": "No Color Palettes Available",
    "stopPosition": "Stop Position",
    "removeSelectedGradientStop": "Remove Selected Gradient Stop",
    "noColor": "No Color",
    "thisElementWillHaveNoColorApplied": "This Element Will Have No Color Applied",
    "yes": "Yes",
    "no": "No",
    "barChart": "Bar Chart",
    "lineChart": "Line Chart",
    "scatterPlot": "Scatter Plot",
    "pieChart": "Pie Chart",
    "areaChart": "Area Chart",
    "radarChart": "Radar Chart",
    "space": "Space",
    "list": "List",
    "category": "Category",
    "values": "Values",
    "xAxisField": "X-Axis Field",
    "yAxisFields": "Y-Axis Fields",
    "selectDataSource": "Select a data source",
    "selectCategoryField": "Select category field",
    "selectXAxisField": "Select X-axis field",
    "selectValueFields": "Select value fields",
    "selectYAxisFields": "Select Y-axis fields",
    "legend": "Legend",
    "hidden": "Hidden",
    "hideLegend": "Hide Legend",
    "showLegend": "Show Legend",
    "legendPosition": "Position",
    "orientation": "Orientation",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "legendTop": "Top",
    "legendBottom": "Bottom",
    "legendLeft": "Left",
    "legendRight": "Right",
    "colorPalette": "Color Palette",
    "defaultPalette": "Default",
    "axisLabels": "Labels",
    "groupBy": "Group By",
    "aggregate": "Aggregate",
    "count": "Count",
    "sum": "Sum",
    "average": "Average",
    "min": "Min",
    "max": "Max",
    "distinct": "Distinct",
    "editFormula": "Edit Formula",
    "right": "Right",
    "showXAxis": "Show X Axis",
    "showXAxisTitle": "Show X Axis Title",
    "showYAxis": "Show Y Axis",
    "showYAxisTitle": "Show Y Axis Title",
    "showXGridlines": "Show X Gridlines",
    "showYGridlines": "Show Y Gridlines",
    "showDataLabels": "Show Data Labels",
    "showDataPoints": "Show Data Points",
    "stacked": "Stacked",
    "newView": "New",
    "calendarView": "Calendar View",
    "dayView": "Day View",
    "weekView": "Week View",
    "monthView": "Month View",
    "closeSpace": "Remove from Focus",
    "customView": "Custom View",
    "detailsView": "Details View",
    "catalogView": "Catalog View",
    "galleryView": "Gallery View",
    "deleteContext": "Delete Context",
    "openSpace": "Open",
    "setNone": "None",
    "applyItems": "Apply to Items in Folder",
    "rename": "Rename",
    "moveFile": "Move File to...",
    "duplicate": "Make a copy",
    "edit": "Edit",
    "delete": "Delete",
    "collapseAllSections": "Collapse All Spaces",
    "expandAllSections": "Expand All Spaces",
    "settings": "Settings",
    "none": "None",
    "tableView": "Table View",
    "cardView": "Card View",
    "boardView": "Board View",
    "listView": "List View",
    "flowView": "Flow View",
    "sortBy": "Sort",
    "filters": "Filters",
    "clearFilters": "Clear Filters",
    "hide": "Hide",
    "unhideFields": "Unhide All Fields",
    "removeFromSpace": "Unpin from ${1}",
    "editCode": "Edit Code",
    "editProperties": "Edit Properties",
    "properties": "Properties",
    "deleteProperty": "Delete Property",
    "hideProperty": "Hide Property",
    "unhideProperty": "Unhide Property",
    "sortAscending": "Sort Ascending",
    "sortDescending": "Sort Descending",
    "deleteRow": "Delete Item",
    "customSort": "Custom Sort",
    "groupSpaces": "Group Spaces",
    "recursiveSort": "Apply to Subfolders",
    "fileNameSortAlphaAsc": "File Name (A to Z)",
    "fileNameSortAlphaDesc": "File Name (Z to A)",
    "fileNameSortNumericalAsc": "File Name (1 to 9)",
    "fileNameSortNumericalDesc": "File Name (9 to 1)",
    "createdTimeSortAsc": "Created Time (new to old)",
    "createdTimeSortDesc": "Created Time (old to new)",
    "modifiedTimeSortAsc": "Modified Time (new to old)",
    "modifiedTimeSortDesc": "Modified Time (old to new)",
    "sizeSortAsc": "Size (smallest to largest)",
    "sizeSortDesc": "Size (largest to smallest)",
    "changeColor": "Color",
    "changePropertyType": "Change Type",
    "folder": "Folder",
    "syncToContext": "Add Property to Context",
    "setIcon": "Set Sticker",
    "copyEmbedLink": "Copy Embed Link",
    "moveUp": "Move Up",
    "moveDown": "Move Down",
    "insertAbove": "Insert Above",
    "insertBelow": "Insert Below",
    "toggleReadMode": "Toggle Read Mode",
    "toggleFullWidth": "Toggle Full Width",
    "openFilePane": "Open File Pane",
    "openNativeMenu": "More Options",
    "revealInDefault": "Reveal in Finder",
    "revealInExplorer": "Reveal in Explorer",
    "showHeader": "Show Header",
    "hideHeader": "Hide Header"
  },
  "editor": {
    "linkName": "${1} Link",
    "linkThumbnail": "${1} Thumbnail",
    "linkSticker": "${1} Sticker",
    "rows": "Rows",
    "columns": "Columns",
    "scaleToFit": "Scale to Fit",
    "scaleToFill": "Scale to Fill",
    "catalog": "Catalog",
    "gallery": "Gallery",
    "grid": "Grid",
    "fit": "Fit",
    "fill": "Fill",
    "stroke": "Stroke",
    "strokeNone": "None",
    "strokeSolid": "Solid",
    "strokeDotted": "Dotted",
    "strokeDashed": "Dashed",
    "size": "Size",
    "gap": "Gap",
    "marginLeft": "Left",
    "marginTop": "Top",
    "marginRight": "Right",
    "marginBottom": "Bottom",
    "minimize": "Minimize",
    "paddingLeft": "Left",
    "paddingTop": "Top",
    "paddingRight": "Right",
    "paddingBottom": "Bottom",
    "unlinkProperty": "Unlink Property",
    "linkedProperty": "Linked Property",
    "linkProperty": "Link Property",
    "currentSpace": "Current Space",
    "opacity": "Opacity",
    "shadowSpread": "Spread",
    "shadowBlur": "Blur",
    "width": "Width",
    "height": "Height",
    "margin": "Margin",
    "padding": "Padding",
    "bold": "Bold",
    "italic": "Italic",
    "underline": "Underline",
    "alignLeft": "Align Left",
    "alignCenter": "Align Center",
    "alignRight": "Align Right",
    "alignJustify": "Align Justify",
    "numberOfLines": "Lines",
    "createVerticalSection": "Create Vertical Section",
    "createHorizontalSection": "Create Horizontal Section"
  },
  "buttons": {
    "close": "Close",
    "back": "Back",
    "add": "Add",
    "import": "Import",
    "cancel": "Cancel",
    "create": "Create",
    "togglePin": "Toggle Pin",
    "refresh": "Refresh",
    "showHidden": "Show Hidden",
    "addFilter": "Add Filter",
    "loadMore": "Load More",
    "addCondition": "Add Condition",
    "customize": "Customize",
    "moreOptions": "More Options",
    "saveProperty": "Save Property",
    "newNote": "New Note",
    "changeIcon": "Sticker",
    "removeIcon": "Remove Sticker",
    "addIcon": "Add Sticker",
    "addCover": "Add Cover",
    "changeBanner": "Change Cover",
    "changeBannerShort": "Cover",
    "removeBanner": "Remove Cover",
    "rename": "Change Name",
    "createFolder": "New Folder",
    "createCanvas": "New Canvas",
    "addIntoSpace": "Pin Item",
    "addSmartSearch": "Add Join",
    "editProperty": "Edit Property",
    "addContext": "Add Tag",
    "delete": "Delete",
    "toggleFlow": "Toggle Flow",
    "openFlow": "Open Flow",
    "hideFlow": "Hide Flow",
    "addToSpace": "Pin File to...",
    "addToSpaceShort": "Pin",
    "tag": "Tag",
    "convertTable": "Convert to Markdown",
    "cutTable": "Cut Table",
    "deleteTable": "Delete From Note",
    "addFile": "Add File",
    "renameView": "Rename View",
    "save": "Save",
    "run": "Run",
    "export": "Export",
    "move": "Move",
    "addTime": "Add Time",
    "addFromExisting": "Add from Existing"
  },
  "metadataTypes": {
    "fileName": "File Name",
    "contexts": "Contexts",
    "isFolder": "Is Folder",
    "path": "Path",
    "folder": "Folder",
    "sticker": "Sticker",
    "color": "Color",
    "created": "Created",
    "lastModified": "Last Modified",
    "extension": "Extension",
    "size": "Size",
    "tags": "Tags",
    "inlinks": "Linked Mentions",
    "outlinks": "Links",
    "label": "Label",
    "fileMetadata": "File Metadata",
    "frontmatter": "Frontmatter"
  },
  "filterTypes": {
    "contains": "contains",
    "notContains": "does not contain",
    "is": "is",
    "isNot": "is not",
    "before": "before",
    "after": "on or after",
    "anyOf": "is any of",
    "noneOf": "is none of",
    "checked": "is checked",
    "unchecked": "is unchecked",
    "isNotEmpty": "is not empty",
    "isEmpty": "is empty",
    "isSameDate": "is same day as",
    "isSameDateAsToday": "is today"
  },
  "sortTypes": {
    "alphaAsc": "A to Z",
    "alphaDesc": "Z to A",
    "earliest": "Earliest",
    "latest": "Latest",
    "checkAsc": "Checked → Unchecked",
    "checkDesc": "Unchecked → Checked",
    "itemsAsc": "Least Items",
    "itemsDesc": "Most Items"
  },
  "properties": {
    "aggregate": {
      "label": "Aggregate",
      "description": "Aggregate functions to calculate values"
    },
    "flex": {
      "label": "Flex",
      "description": "Flexible field to display any type of data"
    },
    "audio": {
      "label": "Audio"
    },
    "text": {
      "label": "Text",
      "description": "Text field"
    },
    "number": {
      "label": "Number",
      "description": "Number field with optional unit"
    },
    "boolean": {
      "label": "Yes/No",
      "description": "Yes or No toggle to indicate the status"
    },
    "date": {
      "label": "Date",
      "description": "Select a date from a calendar"
    },
    "option": {
      "label": "Option",
      "description": "Select one or multiple option from a list"
    },
    "file": {
      "label": "File"
    },
    "link": {
      "label": "Link",
      "description": "Link to another note or a website"
    },
    "tags": {
      "label": "Tags",
      "description": "Use tags to quickly organize your items"
    },
    "object": {
      "label": "Object",
      "description": "Store any complex objects"
    },
    "context": {
      "label": "Context",
      "description": "Context property type"
    },
    "image": {
      "label": "Image",
      "description": "Select any image from your system or from the internet"
    },
    "color": {
      "label": "Color",
      "description": "Use colors to label your items or status"
    },
    "space": {
      "label": "Context",
      "description": "Link to a context"
    },
    "icon": {
      "label": "Sticker",
      "description": "Use stickers to uniquely label your items or status"
    },
    "super": {
      "label": "Super Property"
    },
    "fileProperty": {
      "name": "Name",
      "label": "Formula",
      "createdTime": "Created",
      "modifiedTime": "Last Edited",
      "sticker": "Sticker",
      "links": "Links",
      "tags": "Tags",
      "spaces": "Spaces",
      "extension": "Extension",
      "size": "Size",
      "parentFolder": "Folder",
      "description": "Use a formula to dynamically display a property"
    }
  },
  "views": {
    "navigator": "Spaces",
    "explorer": "Explorer"
  },
  "labels": {
    "base0": "Base0",
    "base10": "Base10",
    "base20": "Base20",
    "base30": "Base30",
    "base40": "Base40",
    "base50": "Base50",
    "base60": "Base60",
    "base70": "Base70",
    "base80": "Base80",
    "base90": "Base90",
    "base100": "Base100",
    "filesCount": "{$1} Files",
    "placeholder": "Type '${1}' for commands",
    "toAppendLinkToTheFile": "to append link to the file",
    "notePlaceholder": "New Note for ${1}",
    "noNotesInside": "No Notes Inside",
    "today": "Today",
    "startTimeProperty": "Start Time Property",
    "endTimeProperty": "End Time Property",
    "startOfDay": "Start Of Day",
    "endOfDay": "End Of Day",
    "itemsSelected": "${1} Selected",
    "createATemplateToGetStarted": "Create a template to get started",
    "iconCount": "${1} icons",
    "iconsIn": "Icons in ${1}",
    "showingFirst": "Showing first ${1} of ${2} icons",
    "createNewItem": "Create New Item",
    "autosaveFailed": "Auto-save failed:",
    "editTitle": "Edit title",
    "removeOption": "Remove option",
    "unknownTransformationError": "Unknown transformation error",
    "center": "Center",
    "position": "Position",
    "top": "Top",
    "bottom": "Bottom",
    "value": "Value",
    "pounds": "Pounds",
    "all": "all",
    "duplicateTable": "Duplicate Table",
    "aggregateBy": "Aggregate By",
    "editFormula": "Edit Formula",
    "editObject": "Edit Object",
    "properties": "Properties",
    "newAction": "Action",
    "newTable": "New Table",
    "rename": "Rename",
    "default": "Default",
    "style": "Style",
    "done": "Done",
    "reposition": "Reposition",
    "tables": "Tables",
    "createSection": "New Folder",
    "createNote": "New Note",
    "select": "Select",
    "pinnedItems": "Pinned Items",
    "making": "Making...",
    "findStickers": "Find Sticker",
    "findStickersButton": "Find",
    "joinItemsFrom": "Join items from",
    "notIncludingSubfolders": "Not including subfolders",
    "includingSubfolders": "Including subfolders",
    "createNewItemsUsing": "Create new items using",
    "withName": "with name",
    "syncWarnings": "The following issues may affect the synchronization of your files. Please review and resolve them.",
    "noWarnings": "No warnings",
    "resolve": "Resolve",
    "ignore": "Ignore",
    "selectNote": "Select Note",
    "selectIcon": "Select Sticker",
    "selectSpace": "Select Space",
    "styleSmall": "Small",
    "styleMedium": "Medium",
    "styleLarge": "Large",
    "hiddenFilePattern": "Name, Suffixes and Extension",
    "hiddenFileSpecific": "Exclude specific files and folders",
    "textPlaceholder": "Enter Text",
    "noFile": "File does not exist yet. Click to create.",
    "blinkPlaceholder": "Search for notes, spaces...",
    "searchPlaceholder": "Type to search...",
    "contextItemSelectPlaceholder": "Find Item",
    "linkItemSelectPlaceholder": "Find or Create Note",
    "pinNotePlaceholder": "Select a Note or Space to Pin",
    "optionItemSelectPlaceholder": "Select Option",
    "tagItemSelectPlaceholder": "Find Tag",
    "spaceSelectPlaceholder": "Select any Folder or Tag",
    "propertyItemSelectPlaceholder": "Select Property",
    "sortItemSelectPlaceholder": "Select Sort",
    "filterItemSelectPlaceholder": "Select Filter",
    "newPaletteName": "New palette name...",
    "newProperty": "New Property",
    "newPropertyShort": "New Property",
    "propertyType": "Type",
    "propertyDynamic": "Dynamic",
    "propertyValueSpace": "Space",
    "propertyValueReference": "Related Property",
    "propertyValueAggregate": "Aggregate Property",
    "propertyValueLinked": "Linked Property",
    "propertyValueLinkedPlaceholder": "Add/Select Property",
    "propertyLookup": "Edit Formula",
    "existingFrontmatter": "Existing Property",
    "dateFormat": "Date Format",
    "numberFormat": "Number Format",
    "editOptions": "Edit Options",
    "checkedSticker": "Checked",
    "uncheckedSticker": "Unchecked",
    "indeterminateSticker": "Unset",
    "propertyFileProp": "Property",
    "multiple": "Multiple",
    "hiddenFiles": "Hidden Files",
    "colors": "Colors",
    "stickers": "Stickers",
    "loadingPalettes": "Loading palettes...",
    "loadingStickerSets": "Loading sticker sets...",
    "manageHiddenFiles": "Manage Hidden Files",
    "addStickerSet": "Add Sticker Set",
    "iconLibrary": "Icon library",
    "emojiLibrary": "Emoji library",
    "builtin": "Built-in",
    "custom": "Custom",
    "dropIconsHere": "Drop icons here to create a new icon set",
    "dropPalettesHere": "Drop JSON palette files here to import",
    "addExtension": "Add Rule",
    "saveView": "Save View",
    "renameView": "Rename View",
    "backlinks": "Backlinks",
    "spaces": "Spaces",
    "content": "Content",
    "deleteSpace": "Delete Space",
    "deleteFiles": "Delete Files",
    "outgoingLinks": "Outgoing Links",
    "moveTo": "Move to",
    "addTo": "Pin to",
    "copyTo": "Copy to",
    "reorderIn": "Reorder in",
    "color": "Color",
    "backgroundColor": "Background",
    "layout": "Layout",
    "name": "Name",
    "alignment": "Alignment",
    "styles": "Styles",
    "actions": "Actions",
    "script": "Script",
    "formula": "Formula",
    "namePlaceholder": "Name",
    "insert": "Insert",
    "allDay": "all day",
    "calculate": "Calculate",
    "noVisualizationConfigured": "No visualization configured",
    "noVisualizationFound": "No visualization found",
    "saveFormula": "Save Formula",
    "selectSticker": "Select Sticker",
    "customize": "Customize",
    "items": "Items",
    "pins": "Pins",
    "joins": "Joins",
    "textStyle": "Text Style",
    "ungroup": "Ungroup",
    "duplicate": "Duplicate",
    "delete": "Delete",
    "list": "List",
    "none": "None",
    "auto": "auto",
    "editPins": "Edit Pins",
    "editJoins": "Edit Joins",
    "editTables": "Edit Tables",
    "exportToHTML": "Export to HTML",
    "applyToItems": "Apply to Items",
    "resetView": "Reset View",
    "resetViewDesc": "Reset the view to the default settings",
    "openASpace": "Open a Space",
    "openASpaceDesc": "Open existing folders and tags as a Space or create a new one",
    "setAsDefault": "Set as Default",
    "thisSpaceAndAllSubfolders": "This Space and All Subfolders",
    "changeCoverShort": "Change Cover",
    "link": "Link",
    "caption": "Caption",
    "colorScheme": "Color Scheme",
    "filesAndFolders": "Files and Folders",
    "lucideIconLibraryForObsidian": "Lucide icon library for Obsidian",
    "emojiIconLibrary": "Emoji icon library",
    "gradients": "Gradients",
    "waypoint": "Waypoint",
    "empty": "Empty",
    "areRequiredForThisLayout": "are required for this layout",
    "showAll": "Show all",
    "limit": "Limit",
    "source": "Source",
    "sizing": "Sizing",
    "interactions": "Interactions",
    "card": "Card",
    "button": "Button",
    "enterTitleForNewItem": "Enter title for new item",
    "functions": "Functions",
    "suggestions": "Suggestions",
    "type": "Type",
    "makeAStaticWebVersionOf": "Make a static web version of",
    "others": "Others",
    "frameHasNoRows": "Frame has no rows",
    "series": "Series:",
    "size": "Size:",
    "label": "Label:",
    "xAxis": "X Axis",
    "yAxis": "Y Axis",
    "unknown": "Unknown",
    "title": "Title",
    "on": "On",
    "quarter": "Quarter",
    "off": "Off",
    "noDataProvided": "No data provided",
    "data": "Data",
    "root": "Root",
    "action": "Action",
    "checklist": "Checklist",
    "home": "Home",
    "frequency": "Frequency",
    "yearly": "Yearly",
    "monthly": "Monthly",
    "weekly": "Weekly",
    "daily": "Daily",
    "hourly": "Hourly",
    "minutely": "Minutely",
    "secondly": "Secondly",
    "until": "Until",
    "interval": "Interval",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "percent": "Percent",
    "sticker": "Sticker",
    "dollars": "Dollars",
    "euros": "Euros",
    "yuan": "Yuan",
    "rupees": "Rupees",
    "won": "Won",
    "francs": "Francs",
    "rands": "Rands",
    "krones": "Krones",
    "rubles": "Rubles",
    "dinars": "Dinars",
    "pesos": "Pesos",
    "rials": "Rials",
    "ringgits": "Ringgits",
    "drachmas": "Drachmas",
    "kuna": "Kuna",
    "forint": "Forint",
    "koruna": "Koruna",
    "dong": "Dong",
    "lira": "Lira",
    "lev": "Lev",
    "zloty": "Zloty",
    "kip": "Kip",
    "tughrik": "Tughrik",
    "rupiah": "Rupiah",
    "liters": "Liters",
    "seconds": "Seconds",
    "scientific": "Scientific",
    "header": "Header",
    "pageHeaderContainingBannerAndTitle": "Page header containing banner and title",
    "banner": "Banner",
    "slides": "Slides",
    "slide": "Slide",
    "delta": "Delta",
    "displayDataWithCustomFieldTypes": "Display data with custom field types",
    "expanded": "Expanded",
    "showFieldLabels": "Show Field Labels",
    "showFieldIcons": "Show Field Icons",
    "status": "Status",
    "subtitle": "Subtitle",
    "prefix": "Prefix",
    "completed": "Completed",
    "due": "Due",
    "fields": "Fields",
    "priority": "Priority",
    "newItemButton": "New Item Button",
    "showNewItemButton": "Show New Item Button",
    "rows": "Rows",
    "columns": "Columns",
    "masonry": "Masonry",
    "countdown": "Countdown",
    "tabs": "Tabs",
    "page": "Page",
    "checkbox": "Checkbox",
    "preview": "Preview",
    "toNavigate": "to navigate",
    "notImplemented": "Not implemented",
    "board": "Board",
    "nineToOne": "9 → 1",
    "xField": "X-Field",
    "yField": "Y-Field",
    "visualization": "Visualization",
    "blink": {
      "items": "Items",
      "recent": "Recent",
      "createNew": "Create New",
      "newNote": "New Note",
      "newSpace": "New Space",
      "results": "Results"
    }
  },
  "descriptions": {
    "defaultMakemlColorPaletteWithThemeColors": "Default Makeml Color Palette With Theme Colors",
    "monochromeColorPaletteWithBaseColors": "Monochrome Color Palette With Base Colors",
    "defaultGradientPaletteWithBeautifulGradients": "Default Gradient Palette With Beautiful Gradients",
    "softPastelColorsForGentleVisualizations": "Soft Pastel Colors For Gentle Visualizations",
    "installing": "Installing",
    "loopOverAList": "Loop Over A List",
    "loop": "Loop",
    "onlyContinueIfAConditionIsMet": "Only Continue If A Condition Is Met",
    "filter": "Filter",
    "useAFormulaToCalculateAResult": "Use A Formula To Calculate A Result",
    "formula": "Formula",
    "creating": "Creating",
    "pasteUrlsHereOnePerLine": "Paste Urls Here One Per Line",
    "pasteYourPaletteJsonHere": "Paste Your Palette Json Here",
    "searchForImagesInYourVaultOrPasteAUrl": "Search For Images In Your Vault Or Paste A Url",
    "getPropertyColor": "Get Property Color",
    "getTheColorForAPropertyValue": "Get The Color For A Property Value",
    "getPropertySticker": "Get Property Sticker",
    "getTheStickericonForAProperty": "Get The Stickericon For A Property",
    "parsePropertyValue": "Parse Property Value",
    "getContentsOfPath": "Get Contents Of Path",
    "getPropertiesOfPath": "Get Properties Of Path",
    "getPathLabel": "Get Path Label",
    "getTheLabelForAPath": "Get The Label For A Path",
    "getPathThumbnail": "Get Path Thumbnail",
    "getTheThumbnailForAPath": "Get The Thumbnail For A Path",
    "writeToPath": "Write To Path",
    "mode": "Mode",
    "append": "Append",
    "getItemsInsideOfPath": "Get Items Inside Of Path",
    "writeToFile": "Write To File",
    "setPathProperty": "Set Path Property",
    "setAPropertyOnAPath": "Set A Property On A Path",
    "showPathContextMenu": "Show Path Context Menu",
    "showContextMenuForAPath": "Show Context Menu For A Path",
    "executeAFormulaWithParameters": "Execute A Formula With Parameters",
    "index": "Index",
    "schema": "Schema",
    "createANewTable": "Create A New Table",
    "openTableRow": "Open Table Row",
    "openATableRow": "Open A Table Row",
    "showTableRowContextMenu": "Show Table Row Context Menu",
    "showContextMenuForATableRow": "Show Context Menu For A Table Row",
    "openTableRowEditModal": "Open Table Row Edit Modal",
    "openEditModalForATableRow": "Open Edit Modal For A Table Row",
    "openTableRowCreateModal": "Open Table Row Create Modal",
    "openCreateModalForANewTableRow": "Open Create Modal For A New Table Row",
    "field": "Field",
    "parseADateString": "Parse A Date String",
    "daysInMonth": "Days In Month",
    "getNumberOfDaysInAMonth": "Get Number Of Days In A Month",
    "formatADateWithAPattern": "Format A Date With A Pattern",
    "format": "Format",
    "getDateComponent": "Get Date Component",
    "getAComponentOfADate": "Get A Component Of A Date",
    "component": "Component",
    "dayOfWeek": "Day Of Week",
    "offsetADateByAnAmount": "Offset A Date By An Amount",
    "offset": "Offset",
    "getTheCurrentDate": "Get The Current Date",
    "getCurrentDate": "Get Current Date",
    "getARangeOfDates": "Get A Range Of Dates",
    "spaceLists": "Create lists to track data and organize them in your space",
    "smartSearch": "Automatically pin notes to this space based on a set of searches",
    "deleteSpace": "Deleting the space will also delete the folder and its contents.",
    "deleteFiles": "Delete ${1} files/folders and their contents?",
    "spaceProperties": "Define Properties for your Space Items",
    "hiddenFileOptions": "Hidden File Options",
    "maxStepsReachedYouCanChangeThisInSettings": "Max steps reached, you can change this in settings."
  },
  "notice": {
    "invalidStickerPackFile": "Invalid Sticker Pack File",
    "fileExists": "File Already Exists",
    "templateSaved": "Template saved to space: ",
    "tableDeleted": "Table removed from Note. You can find the table in the folder Space",
    "copyError": "Copy Error",
    "reload": "Reload",
    "error": "Error: ",
    "cantConvertNoteToSpace": "Can't Convert Note to Space",
    "newSpaceName": "New Space Name",
    "duplicateSpaceName": "Duplicate Space Name",
    "noPropertyName": "No Property Name",
    "duplicatePropertyName": "Duplicate Property Name",
    "palette": "Palette",
    "noPropertiesFound": "No Properties Found",
    "somethingWentWrong": "Something Went Wrong",
    "noExistingValues": "No Existing Values"
  },
  "settings": {
    "importUrls": "Import Urls",
    "exportUrls": "Export Urls",
    "removeImage": "Remove Image",
    "color1": "Color1",
    "dropColorPaletteHereToImport": "Drop Color Palette Here To Import",
    "nameOfYourSystem": "Name Of Your System",
    "stickerPack": "Sticker Pack",
    "other": "Other",
    "dropLanguagePackHereToImport": "Drop Language Pack Here To Import",
    "flow": "Flow",
    "untitled": "Untitled",
    "tags": "Tags",
    "vault": "Vault",
    "title": "Settings",
    "tooltips": {
      "deletePalette": "Delete palette",
      "resetToDefault": "Reset to default",
      "removeColor": "Remove color",
      "addColor": "Add color",
      "deleteStickerSet": "Delete sticker set",
      "addGradientStop": "Add gradient stop",
      "stopPosition": "Stop position (%)",
      "removeGradientStop": "Remove selected gradient stop",
      "importPalette": "Import palette from JSON",
      "exportPalette": "Export palette to JSON",
      "invalidPaletteFormat": "Invalid palette file format. Must have 'name' and 'colors' array.",
      "invalidJSON": "Invalid JSON format"
    },
    "ariaLabels": {
      "noColorApplied": "This element will have no color applied.",
      "closeOnboarding": "Close onboarding",
      "dataSource": "Data Source",
      "chartType": "Chart Type",
      "legendConfiguration": "Legend Configuration",
      "colorConfiguration": "Color Configuration",
      "close": "Close",
      "toggleXAxis": "Toggle X Axis",
      "toggleXAxisLabel": "Toggle X Axis Label",
      "toggleXGridlines": "Toggle X Gridlines",
      "toggleXAxisLine": "Toggle X Axis Line",
      "toggleStackedMode": "Toggle Stacked Mode",
      "toggleYAxis": "Toggle Y Axis",
      "toggleYAxisLabel": "Toggle Y Axis Label",
      "toggleDataLabels": "Toggle Data Labels",
      "toggleYGridlines": "Toggle Y Gridlines",
      "toggleYAxisLine": "Toggle Y Axis Line",
      "toggleLegend": "Toggle Legend",
      "legendPosition": "Legend Position",
      "legendAlignment": "Legend Alignment",
      "toggleLineSmoothing": "Toggle Line Smoothing",
      "toggleStroke": "Toggle Stroke",
      "toggleDataPoints": "Toggle Data Points",
      "toggleDonutChart": "Toggle Donut Chart"
    },
    "onboarding": {
      "welcome": "Welcome to Make.md",
      "welcomeDesc": "Welcome to Make.md! Let's configure your essential settings to get you started.",
      "walkthrough": "We'll walk through the most important options to customize your experience.",
      "coreFeatures": "Core Features",
      "enableNavigator": "Enable Spaces (sidebar file browser)",
      "enableNavigatorDesc": "Show the enhanced file navigator in the sidebar",
      "enableSpaceViews": "Enable Space Views",
      "enableSpaceViewsDesc": "Create custom views and organize content in spaces",
      "enableContexts": "Enable Contexts & Properties",
      "enableContextsDesc": "Add structured data and metadata to your notes",
      "interfacePreferences": "Interface Preferences",
      "showBanners": "Show Note Banners",
      "showBannersDesc": "Display banner images at the top of notes",
      "showFileIcons": "Show File Icons",
      "showFileIconsDesc": "Display custom icons next to files and folders",
      "systemName": "System Name",
      "systemNameDesc": "Customize the name of your workspace",
      "previous": "Previous",
      "next": "Next",
      "skipTour": "Skip Tour",
    },
    "categories": {
      "core": "Core",
      "appearance": "Appearance",
      "system": "System"
    },
    "sections": {
      "general": "General",
      "navigator": "Spaces",
      "appearance": "Appearance",
      "coverImage": "Cover Image",
      "interaction": "Preferences",
      "context": "Context",
      "label": "Labels",
      "tags": "Tags",
      "space": "Spaces",
      "performance": "Performance",
      "advanced": "Advanced",
      "notes": "Notes",
      "assets": "Assets",
      "language": "Language",
      "colors": "Colors",
      "stickers": "Stickers",
      "hidden": "Hidden Files"
    },
    "cacheIndex": {
      "name": "Cache Search Index",
      "desc": "Cache the index for faster search results"
    },
    "layoutVertical": "Vertical",
    "layoutHorizontal": "Horizontal",
    "sectionGeneral": "General",
    "sectionSidebar": "Spaces",
    "sectionEditor": "Maker Mode",
    "sectionFlow": "Flow",
    "sectionAdvanced": "Advanced",
    "sectionDataview": "Dataview",
    "sectionContext": "Context",
    "sectionStickers": "Labels",
    "sectionNavigator": "Spaces",
    "sectionDefault": "Default Spaces",
    "sectionBlink": "Blink",
    "sectionInlineContext": "Inline Context",
    "sectionFlowBlock": "Flow Block",
    "sectionFlowMenu": "Flow Menu",
    "sectionFlowStyler": "Flow Styler",
    "hiddenExtensions": {
      "name": "Hidden Extensions",
      "desc": "File extensions and names to hide from the Spaces"
    },
    "minimalThemeFix": {
      "name": "Minimal Theme Fix",
      "description": "Apply fixes for the popular theme Minimal"
    },
    "inlineStickerMenu": {
      "name": "Inline Stickers",
      "desc": "Add inline stickers by typing :"
    },
    "openSpacesOnLaunch": {
      "name": "Open Spaces as Default Tab",
      "desc": "Open the Spaces tab when Obsidian launches"
    },
    "overrideNativeMenu": {
      "name": "Use Obsidian Context Menu",
      "desc": "Show the Obsidian context menu instead of Make.md"
    },
    "editStickerInSidebar": {
      "name": "Edit Stickers in Sidebar",
      "desc": "Edit stickers directly in the sidebar"
    },
    "autoAddContextsToSubtags": {
      "name": "Apply Properties to Subtags",
      "desc": "Automatically apply context properties to subtags"
    },
    "folderIndentationLines": {
      "name": "Show Folder Indentation Lines",
      "desc": "Turn on to show a line on the left of folders to indicate indentation"
    },
    "internalLinkFlowEditor": {
      "name": "Show Toggles to Open Flow Editor on Links",
      "desc": "Turn on to toggle Flow Blocks directly in inline links"
    },
    "internalLinkSticker": {
      "name": "Show Stickers on Links",
      "desc": "Turn on to toggle stickers shown directly by beside internal links"
    },
    "banners": {
      "name": "Cover Image",
      "desc": "Show a cover image for notes and spaces"
    },
    "expandFolderOnClick": {
      "name": "Auto Expand Folder",
      "desc": "Auto expand folders on click"
    },
    "filePreviewOnHover": {
      "name": "Preview on Hover",
      "desc": "Preview on Hover while holding Control/Command key"
    },
    "revealActiveFile": {
      "name": "Reveal Active File",
      "desc": "Automatically reveal the active file in Spaces"
    },
    "spacesStickers": {
      "name": "Stickers",
      "desc": "Use Emojis to make it easier to find your notes"
    },
    "deleteFileOption": {
      "name": "Delete File Option",
      "desc": "Select how you want files to be deleted"
    },
    "spacesDeleteOptions": {
      "permanent": "Delete Permanently",
      "trash": "Move to Obsidian Trash",
      "system-trash": "Move to System Trash"
    },
    "defaultSpaces": {
      "name": "Default Spaces",
      "desc": "Recommended Spaces for quickly organizing your vault"
    },
    "homeSpace": {
      "name": "Home Space",
      "desc": "An easy-to-access space where you can add/organize your other spaces"
    },
    "enableDefaultSpaces": {
      "name": "Tag Spaces",
      "desc": "Automatically create spaces for each of your tags"
    },
    "readableLineWidth": {
      "name": "Readable Line Width",
      "desc": "Use Readable Line Width"
    },
    "indexSVG": {
      "name": "Use SVGs as Stickers",
      "desc": "Use any svg file in your vault as a sticker"
    },
    "language": {
      "name": "Customize Interface Language",
      "desc": "Modify any text in the interface. Changes require a reload to take effect.",
      "loadingSettings": "Loading language settings...",
      "exportJSON": "Export JSON",
      "importJSON": "Import JSON",
      "importJSONDesc": "Paste your language JSON here. Only modified values will be imported.",
      "pasteJSONPlaceholder": "Paste your JSON here...",
      "import": "Import",
      "cancel": "Cancel",
      "copied": "Copied!",
      "resetAll": "Reset All",
      "search": "Search",
      "searchDesc": "Search by key or text value",
      "showingCount": "Showing {{filtered}} of {{total}} strings",
      "original": "Original",
      "invalidJSON": "Invalid JSON format. Please check your input."
    },
    "inlineStyler": {
      "name": "Flow Styler",
      "desc": "Select text to add styling"
    },
    "inlineStylerColor": {
      "name": "Text and Highlight Colors 🧪",
      "desc": "Select text color and highlight color, (this may change in the future because of the limitations with HTML and Obsidian)"
    },
    "spaceRowHeight": {
      "name": "Row Height",
      "desc": "The height for each row in navigator (in pixels), default is 29"
    },
    "bannerHeight": {
      "name": "Cover Height",
      "desc": "The height for the cover of the note or space, default is 200"
    },
    "makeChar": {
      "name": "Flow Menu Trigger",
      "desc": "Character to open the Flow Menu"
    },
    "mobileMakeBar": {
      "name": "Flow Styler (Mobile)",
      "desc": "Replaces the mobile toolbar"
    },
    "editorMarkSans": {
      "name": "Mark Sans 🧪",
      "desc": "Use the editor without Markdown."
    },
    "editorMakePlaceholder": {
      "name": "Flow Menu Hint Text",
      "desc": "Show a hint text on how to open the Flow Menu Shortcut"
    },
    "blinkEnabled": {
      "name": "Blink",
      "desc": "A faster way to search and edit your notes"
    },
    "editorMakeMenu": {
      "name": "Flow Menu",
      "desc": "Open the Flow menu to quickly add content"
    },
    "editorMakeMenuTrigger": {
      "name": "Flow Menu Shortcut",
      "desc": "Trigger key to use flow menu"
    },
    "editorFlowReplace": {
      "name": "Flow Block",
      "desc": "Open your internal links or toggle your embeds in the flow block."
    },
    "editorFlowStyle": {
      "name": "Flow Block Style",
      "desc": "Select a theme for your flow block",
      "seamless": "Seamless",
      "minimal": "Minimal"
    },
    "noVisualizationConfigured": {
      "name": "No visualization configured",
      "desc": "No visualization configured"
    },
    "maxStepsReachedYouCanChangeThisInSettings": {
      "name": "Max steps reached, you can change this in settings.",
      "desc": "Max steps reached, you can change this in settings."
    }
  },
  "colors": {
    "red": "Red",
    "pink": "Pink",
    "orange": "Orange",
    "yellow": "Yellow",
    "green": "Green",
    "turquoise": "Turquoise",
    "teal": "Teal",
    "blue": "Blue",
    "purple": "Purple",
    "brown": "Brown",
    "charcoal": "Charcoal",
    "gray": "Gray",
    "gold": "Gold",
    "plum": "Plum",
    "khaki": "Khaki",
    "moccasin": "Moccasin",
    "lavender": "Lavender"
  },
  "units": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "yen": "Yen",
    "baht": "Baht",
    "ounces": "Ounces",
    "miles": "Miles",
    "feet": "Feet",
    "inches": "Inches",
    "centimeters": "Centimeters",
    "millimeters": "Millimeters",
    "kilograms": "Kilograms",
    "grams": "Grams"
  },
  "formulas": {
    "prop": "Get the value of a property",
    "slice": "Get a part of a text",
    "if": "If condition is true return the first argument else return the second",
    "ifs": "If the first condition is true return the first argument else check the next condition",
    "empty": "Check if a list is empty",
    "length": "Get the length of a list",
    "values": "Get the number of values in a list",
    "uniques": "Get the number of unique values in a list",
    "substring": "Get a substring of a string",
    "startsWith": "Check if a string starts with another string",
    "contains": "Check if a string contains another string",
    "test": "Test a string with a regex",
    "match": "Match a string with a regex",
    "replace": "Replace a string with another string",
    "replaceAll": "Replace all occurences of a string with another string",
    "lower": "Convert a string to lowercase",
    "upper": "Convert a string to uppercase",
    "repeat": "Repeat a string",
    "format": "Format a value to string",
    "toNumber": "Convert a value to a number",
    "now": "Get the current date",
    "minute": "Get the minutes of a date",
    "hour": "Get the hours of a date",
    "day": "Get the day of a date",
    "date": "Get the date of a date",
    "week": "Get the week of a date",
    "month": "Get the month of a date",
    "year": "Get the year of a date",
    "pad": "Pad a number with text",
    "range": "Get the difference between the largest and smallest from a list of numbers",
    "latest": "Get the latest date of a list of dates",
    "earliest": "Get the earliest date of a list of dates",
    "dateRange": "Get the date range of a list of dates",
    "dateAdd": "Add an amount to a date",
    "dateSubtract": "Subtract an amount from a date",
    "dateBetween": "Get the difference between two dates",
    "spaceItems": "Get the items inside of a path",
    "spaces": "Get the spaces the path is inside of",
    "timeStamp": "Get the timestamp of a date",
    "at": "Get an element at a specific index",
    "first": "Get the first element of a list",
    "last": "Get the last element of a list",
    "concat": "Concatenate two lists",
    "sort": "Sort a list",
    "reverse": "Reverse a list",
    "join": "Turn a list into text separator",
    "includes": "Check if a list includes a value",
    "split": "Split text into a list using a separator",
    "formatDate": "Format a date into text",
    "parseDate": "Transform date from text",
    "find": "Find an element in a list",
    "findIndex": "Find the index of an element in a list",
    "filter": "Filter a list based on a condition",
    "map": "Change all the values in a list based on a formula",
    "some": "Check if some elements in a list are true",
    "every": "Check if every element in a list is true",
    "flat": "Flatten a list of lists into a single list",
    "path": "Get the path object of a path",
    "let": "Define a variable to use in a formula",
    "lets": "Define multiple variables to use in a formula"
  }
};
