export const en = {
    hintText: {
        // fileName: "Enter File Name",
        // alias: "Enter Display Name",
        // newItem: "+ New",
        // selectNote: "Select Note...",
        // createListItem: "Create List Item",
        // dragDropProperties: "Drag and drop to reorder properties",
        dragDropModifierKeys: "Hold Alt to copy",
        // hiddenExtensionsPlaceholder: "e.g., .mdb, _assets",
    },
    // fieldTypes: {
    //     object: "Object",
    //     text: "Text",
    //     file: "File",
    //     date: "Date",
    //     number: "Number",
    // },
    defaults: {
        spaceNote: "Current Note",
        spaceContext: "Current Space",
    },
    // commands: {
    //     h1: "Heading 1",
    //     h2: "Heading 2",
    //     h3: "Heading 3",
    //     h4: "Heading 4",
    //     h5: "Heading 5",
    //     h6: "Heading 6",
    //     columns: "Columns",
    //     tabs: "Tabs",
    //     button: "Button",
    //     label: "Label",
    //     column: "Column",
    //     idea: "New",
    //     group: "Group",
    //     paragraph: "Text",
    //     card: "Card",
    //     cardDesc: "Card container with styled background",
    //     progress: "Progress",
    //     rating: "Rating",
    //     circularProgress: "Circular Progress",
    //     list: "Bullet List",
    //     "ordered-list": "Numbered List",
    //     todo: "To-do List",
    //     quote: "Quote",
    //     internal: "Link to Note",
    //     context: "Embed Existing Context",
    //     flowEmbed: "Embed Note or Space",
    //     board: "New Board",
    //     divider: "Divider",
    //     note: "Note Block",
    //     link: "Web Link",
    //     internalLink: "Link",
    //     callout: "Callout",
    //     bookmark: "Bookmark",
    //     table: "New Table",
    //     codeblock: "Code Block",
    //     toggle: "Toggle",
    //     emoji: "Emoji",
    //     image: "Image",
    //     chart: "Chart",
    //     newNote: "Note",
    //     tag: "tag",
    //     makeMenu: "Flow Menu",
    //     selectStyle: "Style",
    //     toggleKeyboard: "Toggle Keyboard",
    //     flow: "Flow",
    // },
    // styles: {
    //     blocklink: "Link to Note",
    //     textColor: "Text Color",
    //     highlight: "Highlight",
    // },
    // commandsSuggest: {
    //     noResult: "No result",
    // },
    commandPalette: {
        // openFlow: "Open Flow Blocks in Selection",
        // closeFlow: "Close Flow Blocks in Selection",
        openSpaces: "Open Spaces",
        // blink: "Blink",
        revealFile: "Reveal File in Spaces",
        pinActiveFileToSpace: "Link Active File to Space",
        // convertPathToSpace: "Convert Path to Space",
    },
    menu: {
        // createItemInSpace: "Create Item in Space",
        // newItemView: "New Item View",
        // noActionsAvailable: "No Actions Available",
        // path: "Path",
        // name: "Name",
        // content: "Content",
        // property: "Property",
        // value: "Value",
        // table: "Table",
        // click: "Click",
        // hover: "Hover",
        // align: "Align",
        // shadow: "Shadow",
        // noFramesAvailable: "No Frames Available",
        // tabName: "Tab Name",
        // removeTab: "Remove Tab",
        // items: "Items",
        // metadata: "Metadata",
        // special: "Special",
        // cardContainerWithStyledBackground: "Card Container With Styled Background",
        // buttonContainerWithStyledAppearance: "Button Container With Styled Appearance",
        up: "Up",
        down: "Down",
        selectmenu: "Selectmenu",
        toggle: "Toggle",
        setDefaultSticker: "Set Default Sticker",
        setDefaultColor: "Set Default Color",
        new: "New",
        // stopPosition: "Stop Position",
        noColor: "No Color",
        thisElementWillHaveNoColorApplied: "This Element Will Have No Color Applied",
        yes: "Yes",
        no: "No",
        // barChart: "Bar Chart",
        // lineChart: "Line Chart",
        // scatterPlot: "Scatter Plot",
        // pieChart: "Pie Chart",
        // areaChart: "Area Chart",
        // radarChart: "Radar Chart",
        // space: "Space",
        // list: "List",
        // category: "Category",
        // values: "Values",
        // xAxisField: "X-Axis Field",
        // yAxisFields: "Y-Axis Fields",
        // selectDataSource: "Select a data source",
        // selectCategoryField: "Select category field",
        // selectXAxisField: "Select X-axis field",
        // selectValueFields: "Select value fields",
        // selectYAxisFields: "Select Y-axis fields",
        // legend: "Legend",
        // hidden: "Hidden",
        // hideLegend: "Hide Legend",
        // showLegend: "Show Legend",
        // legendPosition: "Position",
        // orientation: "Orientation",
        // horizontal: "Horizontal",
        // vertical: "Vertical",
        // legendTop: "Top",
        // legendBottom: "Bottom",
        // legendLeft: "Left",
        // legendRight: "Right",
        // colorPalette: "Color Palette",
        // defaultPalette: "Default",
        // axisLabels: "Labels",
        // groupBy: "Group By",
        // aggregate: "Aggregate",
        // count: "Count",
        // sum: "Sum",
        // average: "Average",
        // min: "Min",
        // max: "Max",
        // distinct: "Distinct",
        // editFormula: "Edit Formula",
        // right: "Right",
        // showXAxis: "Show X Axis",
        // showXAxisTitle: "Show X Axis Title",
        // showYAxis: "Show Y Axis",
        // showYAxisTitle: "Show Y Axis Title",
        // showXGridlines: "Show X Gridlines",
        // showYGridlines: "Show Y Gridlines",
        // showDataLabels: "Show Data Labels",
        // showDataPoints: "Show Data Points",
        // stacked: "Stacked",
        // newView: "New",
        // calendarView: "Calendar View",
        // dayView: "Day View",
        // weekView: "Week View",
        // monthView: "Month View",
        closeSpace: "Remove from Focus",
        // customView: "Custom View",
        // detailsView: "Details View",
        // catalogView: "Catalog View",
        // galleryView: "Gallery View",
        // deleteContext: "Delete Context",
        openSpace: "Open",
        // setNone: "None",
        applyItems: "Apply to Items in Folder",
        rename: "Rename",
        moveFile: "Move to...",
        duplicate: "Duplicate",
        // edit: "Edit",
        delete: "Delete",
        collapseAllSections: "Collapse All Spaces",
        expandAllSections: "Expand All Spaces",
        settings: "Settings",
        // none: "None",
        // tableView: "Table View",
        // cardView: "Card View",
        // boardView: "Board View",
        // listView: "List View",
        // flowView: "Flow View",
        sortBy: "Sort",
        // filters: "Filters",
        // clearFilters: "Clear Filters",
        hide: "Hide",
        // unhideFields: "Unhide All Fields",
        removeFromSpace: 'Unlink from "${1}"',
        // editCode: "Edit Code",
        // editProperties: "Edit Properties",
        // properties: "Properties",
        // deleteProperty: "Delete Property",
        // hideProperty: "Hide Property",
        // unhideProperty: "Unhide Property",
        // sortAscending: "Sort Ascending",
        // sortDescending: "Sort Descending",
        // deleteRow: "Delete Item",
        customSort: "Custom Sort",
        groupSpaces: "Folders at the Top",
        recursiveSort: "Apply to Subfolders",
        fileNameSortAlphaAsc: "File Name (A to Z)",
        fileNameSortAlphaDesc: "File Name (Z to A)",
        fileNameSortNumericalAsc: "File Name (1 to 9)",
        fileNameSortNumericalDesc: "File Name (9 to 1)",
        createdTimeSortAsc: "Created Time (new to old)",
        createdTimeSortDesc: "Created Time (old to new)",
        modifiedTimeSortAsc: "Modified Time (new to old)",
        modifiedTimeSortDesc: "Modified Time (old to new)",
        changeColor: "Color",
        // changePropertyType: "Change Type",
        folder: "folders",
        // syncToContext: "Add Property to Context",
        // setIcon: "Set Sticker",
        // copyEmbedLink: "Copy Embed Link",
        // moveUp: "Move Up",
        // moveDown: "Move Down",
        // insertAbove: "Insert Above",
        // insertBelow: "Insert Below",
        // toggleReadMode: "Toggle Read Mode",
        // toggleFullWidth: "Toggle Full Width",
        openFilePane: "Open File Pane",
        openNativeMenu: "More options",
        revealInDefault: "Reveal in Finder",
        revealInExplorer: "Reveal in Explorer",
        // showHeader: "Show Header",
        // hideHeader: "Hide Header",
    },
    buttons: {
        close: "Close",
        // back: "Back",
        add: "Add",
        // import: "Import",
        cancel: "Cancel",
        // create: "Create",
        // togglePin: "Toggle Pin",
        // refresh: "Refresh",
        // showHidden: "Show Hidden",
        // addFilter: "Add Filter",
        // loadMore: "Load More",
        // addCondition: "Add Condition",
        // customize: "Customize",
        // moreOptions: "More options",
        // saveProperty: "Save Property",
        // newNote: "New Note",
        changeIcon: "Sticker",
        // removeIcon: "Remove Sticker",
        // addIcon: "Add Sticker",
        // addCover: "Add Cover",
        // changeBanner: "Change Cover",
        // changeBannerShort: "Cover",
        // removeBanner: "Remove Cover",
        rename: "Change Name",
        createFolder: "New Folder",
        createCanvas: "New Canvas",
        createDrawing: "New Drawing",
        createBase: "New Base",
        addIntoSpace: "Link Item",
        // addSmartSearch: "Add Join",
        // editProperty: "Edit Property",
        // addContext: "Add Tag",
        delete: "Delete",
        addToSpace: "Link to...",
        tag: "tags",
        // convertTable: "Convert to Markdown",
        // cutTable: "Cut Table",
        // deleteTable: "Delete From Note",
        addFile: "Add File",
        // renameView: "Rename View",
        save: "Save",
        // run: "Run",
        // export: "Export",
        // move: "Move",
        // addTime: "Add Time",
        // addFromExisting: "Add from Existing",
    },
    // sortTypes: {
    //     alphaAsc: "A to Z",
    //     alphaDesc: "Z to A",
    //     earliest: "Earliest",
    //     latest: "Latest",
    //     checkAsc: "Checked → Unchecked",
    //     checkDesc: "Unchecked → Checked",
    //     itemsAsc: "Least Items",
    //     itemsDesc: "Most Items",
    // },
    // views: {
    //     navigator: "Spaces",
    //     explorer: "Explorer",
    // },
    labels: {
        filesCount: "{$1} Files",
        // placeholder: "Type '${1}' for commands",
        // toAppendLinkToTheFile: "to append link to the file",
        // notePlaceholder: "New Note for ${1}",
        // noNotesInside: "No Notes Inside",
        // today: "Today",
        // startTimeProperty: "Start Time Property",
        // endTimeProperty: "End Time Property",
        // startOfDay: "Start Of Day",
        // endOfDay: "End Of Day",
        // itemsSelected: "${1} Selected",
        // createATemplateToGetStarted: "Create a template to get started",
        // iconCount: "${1} icons",
        // iconsIn: "Icons in ${1}",
        // showingFirst: "Showing first ${1} of ${2} icons",
        // createNewItem: "Create New Item",
        // autosaveFailed: "Auto-save failed:",
        // editTitle: "Edit title",
        // removeOption: "Remove option",
        // unknownTransformationError: "Unknown transformation error",
        // center: "Center",
        // position: "Position",
        // top: "Top",
        // bottom: "Bottom",
        // value: "Value",
        // pounds: "Pounds",
        all: "all",
        // duplicateTable: "Duplicate Table",
        // aggregateBy: "Aggregate By",
        // editFormula: "Edit Formula",
        // editObject: "Edit Object",
        // properties: "Properties",
        // newAction: "Action",
        // newTable: "New Table",
        rename: "Rename",
        // default: "Default",
        // style: "Style",
        // done: "Done",
        // reposition: "Reposition",
        // tables: "Tables",
        createSection: "New Folder",
        createNote: "New Note",
        // select: "Select",
        // pinnedItems: "Pinned Items",
        // making: "Making...",
        findStickers: "Enter sticker keyword",
        findStickersButton: "Find",
        // joinItemsFrom: "Join items from",
        // notIncludingSubfolders: "Not including subfolders",
        // includingSubfolders: "Including subfolders",
        // createNewItemsUsing: "Create new items using",
        // withName: "with name",
        // syncWarnings: "The following issues may affect the synchronization of your files. Please review and resolve them.",
        // noWarnings: "No warnings",
        // resolve: "Resolve",
        // ignore: "Ignore",
        // selectNote: "Select Note",
        // selectIcon: "Select Sticker",
        // selectSpace: "Select Space",
        // styleSmall: "Small",
        // styleMedium: "Medium",
        // styleLarge: "Large",
        hiddenFilePattern: "Name, Suffixes and Extension",
        hiddenFileSpecific: "Exclude specific files and folders",
        // textPlaceholder: "Enter Text",
        // noFile: "File does not exist yet. Click to create.",
        // blinkPlaceholder: "Search for notes, spaces...",
        // searchPlaceholder: "Type to search...",
        // contextItemSelectPlaceholder: "Find Item",
        linkItemSelectPlaceholder: "Find or Create Note",
        pinNotePlaceholder: "Select a Note or Space to Link",
        optionItemSelectPlaceholder: "Select Option",
        // tagItemSelectPlaceholder: "Find Tag",
        spaceSelectPlaceholder: "Select any Folder or Tag",
        // propertyItemSelectPlaceholder: "Select Property",
        // sortItemSelectPlaceholder: "Select Sort",
        // filterItemSelectPlaceholder: "Select Filter",
        // newPaletteName: "New palette name...",
        // newProperty: "New Property",
        // newPropertyShort: "New Property",
        // propertyType: "Type",
        // propertyDynamic: "Dynamic",
        // propertyValueSpace: "Space",
        // propertyValueReference: "Related Property",
        // propertyValueAggregate: "Aggregate Property",
        // propertyValueLinked: "Linked Property",
        // propertyValueLinkedPlaceholder: "Add/Select Property",
        // propertyLookup: "Edit Formula",
        // existingFrontmatter: "Existing Property",
        // dateFormat: "Date Format",
        // numberFormat: "Number Format",
        // editOptions: "Edit Options",
        // checkedSticker: "Checked",
        // uncheckedSticker: "Unchecked",
        // indeterminateSticker: "Unset",
        // propertyFileProp: "Property",
        // multiple: "Multiple",
        hiddenFiles: "Hidden Files",
        // colors: "Colors",
        // stickers: "Stickers",
        // loadingPalettes: "Loading palettes...",
        // loadingStickerSets: "Loading sticker sets...",
        manageHiddenFiles: "Manage Hidden Files",
        // addStickerSet: "Add Sticker Set",
        // iconLibrary: "Icon library",
        // emojiLibrary: "Emoji library",
        // builtin: "Built-in",
        // custom: "Custom",
        // dropIconsHere: "Drop icons here to create a new icon set",
        // dropPalettesHere: "Drop JSON palette files here to import",
        addExtension: "Add Rule",
        saveView: "Save View",
        // renameView: "Rename View",
        // backlinks: "Backlinks",
        // spaces: "Spaces",
        // content: "Content",
        closeFocus: "Close \"${1}\" Focus?",
        deleteFolder: "Delete Folder",
        deleteFiles: "Delete Files",
        // outgoingLinks: "Outgoing Links",
        moveTo: "Move to",
        addTo: "Pin to",
        copyTo: "Copy to",
        reorderIn: "Reorder in",
        // color: "Color",
        // backgroundColor: "Background",
        // layout: "Layout",
        // name: "Name",
        // alignment: "Alignment",
        // styles: "Styles",
        // actions: "Actions",
        // script: "Script",
        // formula: "Formula",
        // namePlaceholder: "Name",
        // insert: "Insert",
        // allDay: "all day",
        // calculate: "Calculate",
        // noVisualizationConfigured: "No visualization configured",
        // noVisualizationFound: "No visualization found",
        // saveFormula: "Save Formula",
        // selectSticker: "Select Sticker",
        // customize: "Customize",
        // items: "Items",
        // pins: "Pins",
        // joins: "Joins",
        // textStyle: "Text Style",
        // ungroup: "Ungroup",
        // duplicate: "Duplicate",
        // delete: "Delete",
        // list: "List",
        // none: "None",
        // auto: "auto",
        // editPins: "Edit Pins",
        // editJoins: "Edit Joins",
        // editTables: "Edit Tables",
        // exportToHTML: "Export to HTML",
        // applyToItems: "Apply to Items",
        // resetView: "Reset View",
        // resetViewDesc: "Reset the view to the default settings",
        openASpace: "Open a Space",
        openASpaceDesc: "Open existing folders and tags as a Space or create a new one",
        // setAsDefault: "Set as Default",
        // thisSpaceAndAllSubfolders: "This Space and All Subfolders",
        // changeCoverShort: "Change Cover",
        // link: "Link",
        // caption: "Caption",
        // colorScheme: "Color Scheme",
        filesAndFolders: "Files and Folders",
        // lucideIconLibraryForObsidian: "Lucide icon library for Obsidian",
        // emojiIconLibrary: "Emoji icon library",
        // gradients: "Gradients",
        waypoint: "Waypoint",
        // empty: "Empty",
        // areRequiredForThisLayout: "are required for this layout",
        // showAll: "Show all",
        // limit: "Limit",
        // source: "Source",
        // sizing: "Sizing",
        // interactions: "Interactions",
        // card: "Card",
        // button: "Button",
        // enterTitleForNewItem: "Enter title for new item",
        // functions: "Functions",
        // suggestions: "Suggestions",
        // type: "Type",
        // makeAStaticWebVersionOf: "Make a static web version of",
        // others: "Others",
        // frameHasNoRows: "Frame has no rows",
        // series: "Series:",
        // size: "Size:",
        // label: "Label:",
        // xAxis: "X Axis",
        // yAxis: "Y Axis",
        // unknown: "Unknown",
        // title: "Title",
        // on: "On",
        // quarter: "Quarter",
        // off: "Off",
        // noDataProvided: "No data provided",
        // data: "Data",
        // root: "Root",
        // action: "Action",
        // checklist: "Checklist",
        home: "Home",
        // frequency: "Frequency",
        // yearly: "Yearly",
        // monthly: "Monthly",
        // weekly: "Weekly",
        // daily: "Daily",
        // hourly: "Hourly",
        // minutely: "Minutely",
        // secondly: "Secondly",
        // until: "Until",
        // interval: "Interval",
        // monday: "Monday",
        // tuesday: "Tuesday",
        // wednesday: "Wednesday",
        // thursday: "Thursday",
        // friday: "Friday",
        // saturday: "Saturday",
        // sunday: "Sunday",
        // percent: "Percent",
        // sticker: "Sticker",
        // dollars: "Dollars",
        // euros: "Euros",
        // yuan: "Yuan",
        // rupees: "Rupees",
        // won: "Won",
        // francs: "Francs",
        // rands: "Rands",
        // krones: "Krones",
        // rubles: "Rubles",
        // dinars: "Dinars",
        // pesos: "Pesos",
        // rials: "Rials",
        // ringgits: "Ringgits",
        // drachmas: "Drachmas",
        // kuna: "Kuna",
        // forint: "Forint",
        // koruna: "Koruna",
        // dong: "Dong",
        // lira: "Lira",
        // lev: "Lev",
        // zloty: "Zloty",
        // kip: "Kip",
        // tughrik: "Tughrik",
        // rupiah: "Rupiah",
        // liters: "Liters",
        // seconds: "Seconds",
        // scientific: "Scientific",
        // header: "Header",
        // pageHeaderContainingBannerAndTitle: "Page header containing banner and title",
        // banner: "Banner",
        // slides: "Slides",
        // slide: "Slide",
        // delta: "Delta",
        // displayDataWithCustomFieldTypes: "Display data with custom field types",
        // expanded: "Expanded",
        // showFieldLabels: "Show Field Labels",
        // showFieldIcons: "Show Field Icons",
        // status: "Status",
        // subtitle: "Subtitle",
        // prefix: "Prefix",
        // completed: "Completed",
        // due: "Due",
        // fields: "Fields",
        // priority: "Priority",
        // newItemButton: "New Item Button",
        // showNewItemButton: "Show New Item Button",
        // rows: "Rows",
        // columns: "Columns",
        // masonry: "Masonry",
        // countdown: "Countdown",
        // tabs: "Tabs",
        // page: "Page",
        // checkbox: "Checkbox",
        // preview: "Preview",
        // toNavigate: "to navigate",
        // notImplemented: "Not implemented",
        // board: "Board",
        // nineToOne: "9 → 1",
        // xField: "X-Field",
        // yField: "Y-Field",
        // visualization: "Visualization",
        // blink: {
        //     items: "Items",
        //     recent: "Recent",
        //     createNew: "Create New",
        //     newNote: "New Note",
        //     newSpace: "New Space",
        //     results: "Results",
        // },
    },
    descriptions: {
        defaultMakemlColorPaletteWithThemeColors: "Default Makeml Color Palette With Theme Colors",
        monochromeColorPaletteWithBaseColors: "Monochrome Color Palette With Base Colors",
        softPastelColorsForGentleVisualizations: "Soft Pastel Colors For Gentle Visualizations",
        // installing: "Installing",
        // loopOverAList: "Loop Over A List",
        // loop: "Loop",
        // onlyContinueIfAConditionIsMet: "Only Continue If A Condition Is Met",
        // filter: "Filter",
        // useAFormulaToCalculateAResult: "Use A Formula To Calculate A Result",
        // formula: "Formula",
        // creating: "Creating",
        // pasteUrlsHereOnePerLine: "Paste Urls Here One Per Line",
        // pasteYourPaletteJsonHere: "Paste Your Palette Json Here",
        // searchForImagesInYourVaultOrPasteAUrl: "Search For Images In Your Vault Or Paste A Url",
        // getPropertyColor: "Get Property Color",
        // getTheColorForAPropertyValue: "Get The Color For A Property Value",
        // getPropertySticker: "Get Property Sticker",
        // getTheStickericonForAProperty: "Get The Stickericon For A Property",
        // parsePropertyValue: "Parse Property Value",
        // getContentsOfPath: "Get Contents Of Path",
        // getPropertiesOfPath: "Get Properties Of Path",
        // getPathLabel: "Get Path Label",
        // getTheLabelForAPath: "Get The Label For A Path",
        // getPathThumbnail: "Get Path Thumbnail",
        // getTheThumbnailForAPath: "Get The Thumbnail For A Path",
        // writeToPath: "Write To Path",
        // mode: "Mode",
        // append: "Append",
        // getItemsInsideOfPath: "Get Items Inside Of Path",
        // writeToFile: "Write To File",
        // setPathProperty: "Set Path Property",
        // setAPropertyOnAPath: "Set A Property On A Path",
        // showPathContextMenu: "Show Path Context Menu",
        // showContextMenuForAPath: "Show Context Menu For A Path",
        // executeAFormulaWithParameters: "Execute A Formula With Parameters",
        // index: "Index",
        // schema: "Schema",
        // createANewTable: "Create A New Table",
        // openTableRow: "Open Table Row",
        // openATableRow: "Open A Table Row",
        // showTableRowContextMenu: "Show Table Row Context Menu",
        // showContextMenuForATableRow: "Show Context Menu For A Table Row",
        // openTableRowEditModal: "Open Table Row Edit Modal",
        // openEditModalForATableRow: "Open Edit Modal For A Table Row",
        // openTableRowCreateModal: "Open Table Row Create Modal",
        // openCreateModalForANewTableRow: "Open Create Modal For A New Table Row",
        // field: "Field",
        // parseADateString: "Parse A Date String",
        // daysInMonth: "Days In Month",
        // getNumberOfDaysInAMonth: "Get Number Of Days In A Month",
        // formatADateWithAPattern: "Format A Date With A Pattern",
        // format: "Format",
        // getDateComponent: "Get Date Component",
        // getAComponentOfADate: "Get A Component Of A Date",
        // component: "Component",
        // dayOfWeek: "Day Of Week",
        // offsetADateByAnAmount: "Offset A Date By An Amount",
        // offset: "Offset",
        // getTheCurrentDate: "Get The Current Date",
        // getCurrentDate: "Get Current Date",
        // getARangeOfDates: "Get A Range Of Dates",
        // spaceLists: "Create lists to track data and organize them in your space",
        // smartSearch: "Automatically pin notes to this space based on a set of searches",
        deleteFolder: "Deleting the folder will also delete its contents.",
        deleteFiles: "Delete ${1} files/folders and their contents?",
        // spaceProperties: "Define Properties for your Space Items",
        hiddenFileOptions: "Hidden File Options",
        // maxStepsReachedYouCanChangeThisInSettings: "Max steps reached, you can change this in settings.",
    },
    notice: {
        fileExists: "File Already Exists",
        copyError: "Copy Error",
        reload: "Reload",
        // error: "Error: ",
        newSpaceName: "New Space Name",
        duplicateSpaceName: "Duplicate Space Name",
        noPropertyName: "No Property Name",
        // duplicatePropertyName: "Duplicate Property Name",
        // palette: "Palette",
        // noPropertiesFound: "No Properties Found",
        somethingWentWrong: "Something Went Wrong",
        // noExistingValues: "No Existing Values",
    },
    settings: {
        // importUrls: "Import Urls",
        // exportUrls: "Export Urls",
        // removeImage: "Remove Image",
        // color1: "Color1",
        // dropColorPaletteHereToImport: "Drop Color Palette Here To Import",
        // nameOfYourSystem: "Name Of Your System",
        // stickerPack: "Sticker Pack",
        // other: "Other",
        // dropLanguagePackHereToImport: "Drop Language Pack Here To Import",
        // flow: "Flow",
        // untitled: "Untitled",
        // tags: "Tags",
        // vault: "Vault",
        // title: "Settings",
        // tooltips: {
        //     deletePalette: "Delete palette",
        //     resetToDefault: "Reset to default",
        //     removeColor: "Remove color",
        //     addColor: "Add color",
        //     deleteStickerSet: "Delete sticker set",
        //     addGradientStop: "Add gradient stop",
        //     stopPosition: "Stop position (%)",
        //     removeGradientStop: "Remove selected gradient stop",
        //     importPalette: "Import palette from JSON",
        //     exportPalette: "Export palette to JSON",
        //     invalidPaletteFormat: "Invalid palette file format. Must have 'name' and 'colors' array.",
        //     invalidJSON: "Invalid JSON format",
        // },
        // language: {
        //     name: "Customize Interface Language",
        //     desc: "Modify any text in the interface. Changes require a reload to take effect.",
        //     loadingSettings: "Loading language settings...",
        //     exportJSON: "Export JSON",
        //     importJSON: "Import JSON",
        //     importJSONDesc: "Paste your language JSON here. Only modified values will be imported.",
        //     pasteJSONPlaceholder: "Paste your JSON here...",
        //     import: "Import",
        //     cancel: "Cancel",
        //     copied: "Copied!",
        //     resetAll: "Reset All",
        //     search: "Search",
        //     searchDesc: "Search by key or text value",
        //     showingCount: "Showing {{filtered}} of {{total}} strings",
        //     original: "Original",
        //     invalidJSON: "Invalid JSON format. Please check your input.",
        // },
        // categories: {
        //     appearance: "Appearance",
        //     system: "System",
        // },

        sections: {
            appearance: "Appearance",
            system: "System",
        },
        spaceRowHeight: {
            name: "Row Height",
            desc: "The height for each row in navigator (in pixels), default is 29",
        },
        folderIndentationLines: {
            name: "Show Folder Indentation Lines",
            desc: "Turn on to show a line on the left of folders to indicate indentation",
        },
        openSpacesOnLaunch: {
            name: "Open Spaces as Default Tab",
            desc: "Open the Spaces tab when Obsidian launches",
        },
        overrideNativeMenu: {
            name: "Use Obsidian Context Menu",
            desc: "Show the Obsidian context menu instead of Make.md",
        },
        expandFolderOnClick: {
            name: "Auto Expand Folder",
            desc: "Auto expand folders on click",
        },
        revealActiveFile: {
            name: "Reveal Active File",
            desc: "Automatically reveal the active file in Spaces",
        },
        deleteFileOption: {
            name: "Delete File Option",
            desc: "Select how you want files to be deleted",
        },

        spacesDeleteOptions: {
            permanent: "Permanent",
            trash: "Trash",
            "system-trash": "System Trash",
        },
    },
    colors: {
        base0: "Base0",
        base10: "Base10",
        base20: "Base20",
        base30: "Base30",
        base40: "Base40",
        base50: "Base50",
        base60: "Base60",
        base70: "Base70",
        base80: "Base80",
        base90: "Base90",
        base100: "Base100",

        red: "Red",
        pink: "Pink",
        orange: "Orange",
        yellow: "Yellow",
        green: "Green",
        turquoise: "Turquoise",
        teal: "Teal",
        blue: "Blue",
        purple: "Purple",
        brown: "Brown",
        charcoal: "Charcoal",
        gray: "Gray",

        lightPink: "Light Pink",
        gold: "Gold",
        paleGreen: "Pale Green",
        skyBlue: "Sky Blue",
        plum: "Plum",
        khaki: "Khaki",
        lightSalmon: "Light Salmon",
        powderBlue: "Powder Blue",
        moccasin: "Moccasin",
        lavender: "Lavender",
    },
};
