import i18n from "shared/i18n";

import { MakeMDSettings } from "../../shared/types/settings";



export const DEFAULT_SETTINGS: MakeMDSettings = {
  defaultInitialization: false,
  filePreviewOnHover: false,
  spacesMDBInHidden: true,
  cacheIndex: true,
  spacesRightSplit: false,
  activeView: "/",
  activeSpace: "",
  defaultDateFormat: "MMM dd yyyy",
  defaultTimeFormat: "h:mm a",
  currentWaypoint: 0,
  enableFolderNote: true,
  folderIndentationLines: true,
  revealActiveFile: false,
  spacesStickers: true,
  spaceRowHeight: 29,
  bannerHeight: 200,
  folderNoteInsideFolder: true,
  folderNoteName: "",
  deleteFileOption: "trash",
  expandedSpaces: ["/"],
  expandFolderOnClick: true,
  hiddenFiles: [],
  hiddenExtensions: [".mdb", '_assets', '_blocks'],
  newFileLocation: "root",
  newFileFolderPath: "",
  inlineBacklinks: false,
  inlineBacklinksExpanded: false,
  banners: true,
  spacesUseAlias: false,
  fmKeyAlias: 'aliases',
  fmKeyBanner: 'banner',
  fmKeyColor: 'color',
  fmKeyBannerOffset: 'banner_y',
  fmKeySticker: 'sticker',

  openSpacesOnLaunch: true,
  indexSVG: false,
  readableLineWidth: true,
  releaseNotesPrompt: 0.8,
  showSpacePinIcon: true,
  experimental: false,
  actionMaxSteps: 100,
  skipFolders: [],
  skipFolderNames: [],
  enhancedLogs: false,
  firstLaunch: false,
  editStickerInSidebar: true,
  overrideNativeMenu: false,
  onboardingCompleted: false,
};
